### ISSUE TITLE
Names with paired double quotes break parsing

### ISSUE THREAD

**Issue by tazfrison** [rcontf/rcon.tf#62]
The regex used to split the player info from status breaks if there are double quotes in the name.  Webpage would error out since it would attempt to parse "Last" as the steamid and fail.
Sample string (identifying information removed) was:
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;48&nbsp;"First "Last""&nbsp;[U:1:123456789]&nbsp;&nbsp;&nbsp;36:36&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;155&nbsp;&nbsp;&nbsp;&nbsp;0&nbsp;active&nbsp;192.148.0.0:27005
src/pages/DashboardPage.tsx:328

**Comment by c43721** [comment]
@tazfrison Fixed in #63.
